export const recipes = [
	{sort: 6, name: "The Cigar", id: "gZdT2GBf91I", ingredients: [
		{n:"Sweet Vermouth", oz: 1.5 },
		{n:"Single Malt Scotch", oz: 1 },
		{n:"Aperol", oz: 0.5 },
	]},
	{sort: 0, name: "Division Bell", id: "70cS-bRH9kA", ingredients: [
		{n:"Mezcal", oz: 1 },
		{n:"Aperol", oz: 3/4 },
		{n:"Marashino Liqueur", oz: 1/2 },
		{n:"Lime Juice", oz: 3/4 }
	]},
	{sort: 14, name: "Bijou", id: "LeIeaxJR2kw", ingredients: [
		{n:"Gin", oz: 1.25 },
		{n:"Sweet Vermouth", oz: 3/4 },
		{n:"Green Charteuse", oz: 1/4 },
		{n:"Orange Bitters"},
	]},
	{sort: 23, name: "La Louisiane", id: "9XLtsOKT6oY", ingredients: [
		{n:"Rye", oz: 1.5 },
		{n:"Sweet Vermouth", oz: 3/4 },
		{n:"Benedictine", oz: 3/4 },
		{n: "Peychauds Bitters"},
		{n: "Angostura Bitters"},
		{n: "Absinthe"},
	]},
	{sort: 17, name: "The Adonis", id: "B8l-F1qcTYU", ingredients: [
		{n:"Oloroso Sherry", oz: 2 },
		{n:"Sweet Vermouth", oz: 1 },
		{n: "Orange Bitters"},
	]},
	{sort: 24, name: "Staggering Gentleman", id: "QFjRjAP-k1k", ingredients: [
		{n:"Bourbon", oz: 2 },
		{n:"Benedictine", oz: 1/2 },
		{n:"Nocino", oz: 1/2 }
	]},
	{sort: 12, name: "The Trinidad Sour", id: "_BEaYWQjSu0", ingredients: [
		{n: "Angostura Bitters", oz: 1},
		{n: "Rye", oz: 1/2},
		{n: "Orgeat", oz: 1},
		{n: "Lemon Juice", oz: 3/4},
		{n: "Mint"},
	]},
	{sort: 19, name: "The Momisette", id: "ABntm6FL8wc", ingredients: [
		{n: "Absinthe", oz: 1.5},
		{n: "Orgeat", oz: 3/4},
		{n: "Lemon Juice", oz: 3/4},
		{n: "Soda"},
	]},
	{sort: 8, name: "The Corpse Reviver #2", id: "bGxOcLRCBWk", ingredients: [
		{n:"Gin", oz: 3/4 },
		{n:"Lillet Blanc", oz: 3/4 },
		{n:"Cointreau", oz: 3/4 },
		{n:"Lemon Juice", oz: 3/4 },
		{n:"Absinthe" }
	]},
	{sort: 2, name: "The Gunshop Fizz", id: "NYKEbNf5ksg", ingredients: [
		{n:"Peychauds Bitters", oz: 2 },
		{n:"Lemon Juice", oz: 1 },
		{n:"Simple Syrup", oz: 1 },
		{n:"Campari", oz: 0.75 },
		{n:"Soda"},
		{n:"Strawberry" },
		{n:"Cucumber" },
		{n:"Orange" },
		{n:"Grapefruit" },
	]},
	{sort: 3, name: "Aku-Aku Gold Cup", id: "PXlotBCibPQ", ingredients: [
		{n:"Light Column Stilled Rum", oz: 1.25 },
		{n:"Aged Jamaican Rum", oz: 1/2 },
		{n:"Falernum", oz: 1/2 },
		{n:"Lemon Juice", oz: 3/4 },
		{n:"Simple Syrup", oz: 1/4 },
	]},
	{sort: 16, name: "Big Bamboo", id: "PEGj0353z7U", ingredients: [
		{n:"Light Column Stilled Rum", oz: 2 },
		{n:"Aged Jamaican Rum", oz: 1 },
		{n:"Lime Juice", oz: 1/2 },
		{n:"Orange Juice", oz: 1/2 },
		{n:"Grapefruit Juice", oz: 1/2 },
		{n:"Passionfruit Syrup", oz: 1/2 },
		{n: "Angostura Bitters"},
	]},
	{sort: 1, name: "The ByWater", id: "1aR4C0yLEeI", ingredients: [
		{n:"Aged Column Stilled Rum", oz: 1.75 },
		{n:"Amaro", oz: 0.75 },
		{n:"Green Charteuse", oz: 0.33 },
		{n:"Falernum", oz: 0.25 },
		{n: "Peychauds Bitters"},
		{n: "Angostura Bitters"},
		{n: "Orange Bitters"},
	]},
	{sort: 20, name: "Champs Élysées", id: "fld-Lcjhxa4", ingredients: [
		{n:"Cognac", oz: 2 },
		{n:"Green Charteuse", oz: 0.5 },
		{n:"Lemon Juice", oz: 0.75 },
		{n:"Simple Syrup", oz: 0.25 },
		{n: "Angostura Bitters"},
	]},
	{sort: 4, name: "Vieux Carre", id: "-KbXFLiIb3c", ingredients: [
		{n:"Cognac", oz: 1 },
		{n:"Rye", oz: 1 },
		{n:"Sweet Vermouth", oz: 1 },
		{n:"Benedictine", oz: 0.75 },
		{n: "Peychauds Bitters"},
		{n: "Angostura Bitters"},
	]},
	{sort: 18, name: "Suffering Bastard", id: "ptQySXcqZOs", ingredients: [
		{n:"Gin", oz: 1.25 },
		{n:"Bourbon", oz: 1.25 },
		{n:"Demerara Syrup", oz: 0.5 },
		{n:"Lime Juice", oz: 1 },
		{n:"Ginger Beer"},
		{n: "Angostura Bitters"},
	]},
	{sort: 5, name: "Tommy's Margarita", id: "RKnx1w54MjU", ingredients: [
		{n:"Tequila", oz: 2 },
		{n:"Lime Juice", oz: 1 },
		{n:"Agave Syrup", oz: 0.75 },
	]},
	{sort: 9, name: "Japanese Cocktail", id: "swWPcFna4q4", ingredients: [
		{n:"Cognac", oz: 2 },
		{n:"Orgeat", oz: 0.5 },
		{n: "Angostura Bitters"},
	]},
	{sort: 19, name: "Dominicana", id: "sQJjDtYQtqE", ingredients: [
		{n:"Aged Jamaican Rum", oz: 1.5 },
		{n:"Coffee Liqueur", oz: 1 },
		{n:"Demerara Syrup", oz: 0.75 },
		{n:"Cream" }
	]},
	{sort: 13, name: "Rabo de Galo", id: "OH54RB-3xeU", ingredients: [
		{n:"Aged Cachaca", oz: 2 },
		{n:"Cynar", oz: 0.75 },
		{n:"Sweet Vermouth", oz: 0.75 },
	]},
	{sort: 7, name: "The Halekulani Cocktail", id: "Wkgpo7ZgenE", ingredients: [
		{n:"Bourbon", oz: 2 },
		{n:"Lemon Juice", oz: 0.5 },
		{n:"Pineapple Juice", oz: 0.5 },
		{n:"Orange Juice", oz: 0.5 },
		{n:"Demerara Syrup", oz: 0.5 },
		{n:"Grenadine" },
		{n: "Angostura Bitters"},
	]},
	{sort: 10, name: "Hey Mambo", id: "gxUgE9sX5aI", ingredients: [
		{n:"Mezcal", oz: 1 },
		{n:"Tequila", oz: 0.5 },
		{n:"Aperol", oz: 1 },
		{n:"Pineapple Juice", oz: 1.5 },
		{n:"Coconut Cream", oz: 1.5 },
		{n:"Lime Juice", oz: 0.5 },
	]},
	{sort: 15, name: "Oaxacanite", id: "pT9DsmQVDSk", ingredients: [
		{n:"Mezcal", oz: 1.25 },
		{n:"Tequila", oz: 1 },
		{n:"Honey Syrup", oz: 1 },
		{n:"Lime Juice", oz: 1 },
		{n: "Angostura Bitters"},
	]},
	{sort: 22, name: "Love and Murder", id: "1lbI9MjHdNo", ingredients: [
		{n:"Green Charteuse", oz: 1 },
		{n:"Campari", oz: 1 },
		{n:"Lime Juice", oz: 1 },
		{n:"Simple Syrup", oz: 0.75 },
	]},
]
