export const recipes = [
	{sort: 1, name: "Saturn", id: "TFp9ybIxlfo", ingredients: [
		{n:"Gin", oz: 5/4 },
		{n:"Lemon Juice", oz: 1/2 },
		{n:"Passionfruit Syrup", oz: 1/2 },
		{n:"Falernum", oz: 1/4 },
		{n:"Orgeat", oz: 1/4 },
	]},
	{sort: 2, name: "Tradewinds Negroni", id: "Lp5ktjaNFKc", ingredients: [
		{n:"Sweet Vermouth", oz: 1.5 },
		{n:"Cointreau", oz: 3/4 },
		{n:"Angostura Bitters", oz: 3/4 },
	]},
	{sort: 3, name: "The Italian Zombie", id: "dJJ7ShFqFLY", ingredients: [
		{n:"Jamaican Rum", oz: 1.5, annotation: "Worthy Park 109" },
		{n:"Funky Jamaican Rum", oz: 1/2, annotation: "Smith and Cross" },
		{n:"Campari", oz: 1 },
		{n:"Pineapple Juice", oz: 2 },
		{n:"Apricot Liqueur", oz: 1/2 },
		{n:"Passionfruit Syrup", oz: 1/2 },
		{n:"Lime Juice", oz: 3/4 },
		{n:"Absinthe", oz: 0 },
		{n:"Angostura Bitters", oz: 0 },
	]},
	{sort: 4, name: "Fog Cutter", id: "XEPtHqQ5DzE", ingredients: [
		{n:"Rhum Agricole Blanc", oz: 1 },
		{n:"Gin", oz: 1/2 },
		{n:"Cognac", oz: 1/2 },
		{n:"Dry Curacao", oz: 1/2 },
		{n:"Amontillado Sherry", oz: 1/2 },
		{n:"Orgeat", oz: 3/4 },
		{n:"Lemon Juice", oz: 1 },
	]},
	{sort: 5, name: "El Presidente", id: "R-EwoGkHHmE", ingredients: [
		{n:"Light Column Still Rum", oz: 1, annotation: "Havana Club 3yr" },
		{n:"Light Column Still Rum", oz: 3/4, annotation: "Flor De Cana 12yr" },
		{n:"Blanc Vermouth", oz: 1 },
		{n:"Dry Curacao", oz: 1/2 },
		{n:"Grenadine", oz: 1/8 },
		{n:"Rhum Agricole Blanc", oz: 1/8 },
		{n:"Peychauds Bitters", oz: 0 },
	]},
	{sort: 6, name: "The Kill Devil Reef", id: "PwchTmkVvxU", ingredients: [
		{n:"Funky Overproof Rum", oz: 1, annotation: "Rum Fire" },
		{n:"151 Demerara Rum", oz: 1, annotation: "Lemonhart 151" },
		{n:"Demerara Rum", oz: 0.5, annotation: "Hamilton Pot Still Demerara" },
		{n:"Rhum Agricole Blanc", oz: 0.5 },
		{n:"Passionfruit Syrup", oz: 1 },
		{n:"Falernum", oz: 1/2 },
		{n:"Honey", oz: 1/2 },
		{n:"Lime Juice", oz: 1 },
	]},
	{sort: 7, name: "Boulevardier", id: "VAK-A7laGuE", ingredients: [
		{n:"Bourbon", oz: 1.5 },
		{n:"Campari", oz: 1 },
		{n:"Sweet Vermouth", oz: 1 },
	]},
	{sort: 8, name: "Queens Park Swizzle", id: "oNPRn-uLAR8", ingredients: [
		{n:"Jamaican Rum", oz: 1, annotation: "Worthy Park 109" },
		{n:"Demerara Rum", oz: 1, annotation: "Hamilton Pot Still Demerara" },
		{n:"Demerara Syrup", oz: 1 },
		{n:"Lime Juice", oz: 1 },
		{n:"Angostura Bitters", oz: 0 },
		{n:"Mint", oz: 0 },
	]},
	{sort: 9, name: "The Tartan Cocktail", id: "Jqy3bhn-O9s", ingredients: [
		{n:"Scotch", oz: 1.5, annotation: "Glenallachie Sherry Cask" },
		{n:"Sweet Vermouth", oz: 3/4 },
		{n:"Amaro", oz: 1/4 },
		{n:"Drambiue", oz: 1/4 },
		{n:"Angostura Bitters", oz: 0 },
	]},
	{sort: 10, name: "Demerara Dry Float", id: "C2jlz4V_jTk", ingredients: [
		{n:"Demerara Rum", oz: 1.5, annotation: "Hamilton Pot Still Demerara" },
		{n:"151 Demerara Rum", oz: 0.5, annotation: "Lemonhart 151" },
		{n:"Jamaican Rum", oz: 0.5, annotation: "Worthy Park 109" },
		{n:"Marashino Liqueur", oz: 0.5 },
		{n:"Passionfruit Syrup", oz: 1 },
		{n:"Lime Juice", oz: 1 },
		{n:"Angostura Bitters", oz: 0 },
	]},
	{sort: 11, name: "The Colonial Ties", id: "YjCp9C1Qqsg", ingredients: [
		{n:"Jamaican Rum", oz: 1, annotation: "Worthy Park 109" },
		{n:"Rye Whisky", oz: 1 },
		{n:"Demerara Syrup", oz: 1/4 },
		{n:"Angostura Bitters", oz: 0 },
		{n:"Peychauds Bitters", oz: 0 },
	]},
	{sort: 12, name: "Monte Cassino", id: "3f-Jzd8AFiM", ingredients: [
		{n:"Rye Whisky", oz: 3/4 },
		{n:"Benedictine", oz: 3/4 },
		{n:"Yellow Chartreuse", oz: 3/4 },
		{n:"Lemon Juice", oz: 3/4 },
	]},
	{sort: 14, name: "Rum Firewalker", id: "dXH6BOSGioE", ingredients: [
		{n:"Funky Overproof Rum", oz: 1.5, annotation: "Rum Fire" },
		{n:"Light Column Still Rum", oz: 1.5, annotation: "Havana Club 3yr" },
		{n:"Campari", oz: 1 },
		{n:"Cinnamon Syrup", oz: 1 },
		{n:"Lime Juice", oz: 1 },
	]},
	{sort: 13, name: "Nuclear Daquiri", id: "KRpkCOWQZ5U", ingredients: [
		{n:"Funky Overproof Rum", oz: 1/2, annotation: "Wray and Nephew Overproof" },
		{n:"Funky Overproof Rum", oz: 1/2, annotation: "Rum Fire" },
		{n:"Green Chartreuse", oz: 1 },
		{n:"Falernum", oz: 1 },
		{n:"Lime Juice", oz: 1 },
	]},
	{sort: 15, name: "Amaretto Sour", id: "vdL8MZX_MKA", ingredients: [
		{n:"Bourbon", oz: 2 },
		{n:"Amaretto", oz: 1 },
		{n:"Lemon Juice", oz: 1 },
	]},
	{sort: 16, name: "Lapu Lapu", id: "s3OWmLQVJaY", ingredients: [
		{n:"Light Column Still Rum", oz: 1.5, annotation: "Havana Club 3yr" },
		{n:"Jamaican Rum", oz: 1, annotation: "Worthy Park 109" },
		{n:"151 Demerara Rum", oz: 0.5, annotation: "Lemonhart 151" },
		{n:"Orange Juice", oz: 2 },
		{n:"Passionfruit Syrup", oz: 1 },
		{n:"Lime Juice", oz: 1/2 },
		{n:"Lemon Juice", oz: 1/2 },
		{n:"Mint", oz: 0 },
	]},
	{sort: 17, name: "The Mai Kai Barrel O' Rum", id: "i7ovdT1w4yU", ingredients: [
		{n:"Jamaican Rum", oz: 1.5, annotation: "Worthy Park 109" },
		{n:"Jamaican Rum", oz: 1/2, annotation: "Appleton Estate" },
		{n:"Funky Overproof Rum", oz: 1/2, annotation: "Wray and Nephew Overproof" },
		{n:"Light Column Still Rum", oz: 1/2, annotation: "Havana Club 3yr" },
		{n:"Passionfruit Syrup", oz: 1 },
		{n:"Honey", oz: 1/2 },
		{n:"Falernum", oz: 1/2 },
		{n:"Grapefruit Juice", oz: 1.5 },
		{n:"Orange Juice", oz: 1 },
		{n:"Angostura Bitters", oz: 0 },
	]},
	{sort: 18, name: "Nui Nui", id: "DLjXocLodV0", ingredients: [
		{n:"Jamaican Rum", oz: 1, annotation: "Appleton Estate" },
		{n:"Jamaican Rum", oz: 1, annotation: "Worthy Park 109" },
		{n:"Dry Curacao", oz: 1/2 },
		{n:"Cinnamon Syrup", oz: 1/2 },
		{n:"Falernum", oz: 1/4 },
		{n:"Vanilla Syrup", oz: 1/4 },
		{n:"Lime Juice", oz: 1 },
		{n:"Angostura Bitters", oz: 0 },
	]},
	{sort: 19, name: "Remember the Maine", id: "I2_xijYpP_Y", ingredients: [
		{n:"Rye Whisky", oz: 3/4 },
		{n:"Bourbon", oz: 3/4 },
		{n:"Sweet Vermouth", oz: 3/4 },
		{n:"Cherry Heering", oz: 1/4 },
		{n:"Absinthe", oz: 0 },
	]},
	{sort: 20, name: "Penang Afrididi", id: "aQq0eLv4Emo", ingredients: [
		{n:"Light Column Still Rum", oz: 1.5, annotation: "Havana Club 3yr" },
		{n:"Jamaican Rum", oz: 1.5, annotation: "Appleton Estate" },
		{n:"Passionfruit Syrup", oz: 3/4 },
		{n:"Lime Juice", oz: 3/4 },
		{n:"Pineapple Juice", oz: 3/4 },
		{n:"Orange Juice", oz: 0.5 },
		{n:"Absinthe", oz: 0 },
		{n:"Mint", oz: 0 },
	]},
	{sort: 21, name: "Pago Pago", id: "tLxrfnYs8ZI", ingredients: [
		{n:"Jamaican Rum", oz: 2, annotation: "Appleton Estate" },
		{n:"Yellow Chartreuse", oz: 1/2 },
		{n:"Creme de Cacao", oz: 1/4 },
		{n:"Pineapple Juice", oz: 3/4 },
		{n:"Lime Juice", oz: 1/2 },
	]},
	{sort: 22, name: "Mai Tai", id: "DCt0I2x5xls", ingredients: [
		{n:"Funky Jamaican Rum", oz: 1/2, annotation: "Smith and Cross" },
		{n:"Jamaican Rum", oz: 1/2, annotation: "Worthy Park 109" },
		{n:"Demerara Rum", oz: 1/2, annotation: "Hamilton Pot Still Demerara" },
		{n:"Funky Overproof Rum", oz: 1/2, annotation: "Wray and Nephew Overproof" },
		{n:"Rhum Agricole Blanc", oz: 1/4 },
		{n:"Dry Curacao", oz: 1/2 },
		{n:"Orgeat", oz: 1/2 },
		{n:"Lime Juice", oz: 1 },
		{n:"Mint", oz: 0 },
		{n:"Lime", oz: 0 },
	]},
	{sort: 23, name: "The Millionaire", id: "CZ5KSKO3sbQ", ingredients: [
		{n:"Bourbon", oz: 1.5 },
		{n:"Jamaican Rum", oz: 0.5, annotation: "Appleton Estate" },
		{n:"Apricot Liqueur", oz: 0.5 },
		{n:"Dry Curacao", oz: 0.5 },
		{n:"Lemon Juice", oz: 1 },
		{n:"Peychauds Bitters", oz: 0 },
		{n:"Egg White", oz: 0 },
		{n:"Nutmeg", oz: 0 },
	]},
	{sort: 24, name: "The Grasshopper", id: "ERHGoHllsq8", ingredients: [
		{n:"Creme de Menthe", oz: 1.5 },
		{n:"Creme de Cacao", oz: 1.5 },
		{n:"Fernet Branca", oz: 1.5 },
		{n:"Vanilla Ice Cream", oz: 0 },
		{n:"Salt", oz: 0 },
	]},
]
